### ISSUE TITLE
Offtopic Question

### ISSUE THREAD

**Issue by pythoneer** [doomrobo/rust-shred#1]
I beg your pardon upfront for hijacking the issue section of this repo but i just did not find any way to contact you. I saw your question on Stackoverflow https://stackoverflow.com/questions/8675797/x11-unicode-keyevent-issues?rq=1  and i am having the exact same issue. I was on the way to solve that exactly the same way you mentioned later in the comments. But something is not working on my code. Do you have an example left on how you did that or could visit my question and code to tell me what i did wrong? https://stackoverflow.com/questions/44313966/c-xtest-emitting-key-presses-for-every-unicode-character

Again, sry for using this method but there is no way to contact people on stackoverflow (or even github) 
best regards!

**Comment by rozbb** [comment]
Looks like it was answered
